"""
ChipGate TinyTapeoutPrep — TinyTapeout wrapper generation.

Generates a tt_um_chipgate_dtl_gate wrapper module that conforms to
TinyTapeout pin conventions (ui_in[0:7], uo_out[0:7], uio_inout, ena, clk, rst_n).

The wrapper instantiates the tiny_dtl_gate core and maps its ports
to the TinyTapeout pinout defined in tt_pinout.py.
"""

from typing import Dict, Optional

from .tt_pinout import (
    INPUT_PINOUT,
    OUTPUT_PINOUT,
    RESERVED_INPUTS,
    RESERVED_OUTPUTS,
    TT_INPUT_WIDTH,
    TT_OUTPUT_WIDTH,
    get_canonical_pinout,
)


def generate_wrapper_verilog(
    core_module: str = "tiny_dtl_gate",
    top_module: str = "tt_um_chipgate_dtl_gate",
    pinout: Optional[Dict[str, str]] = None,
) -> str:
    """Generate a TinyTapeout-compatible wrapper in Verilog.

    Args:
        core_module: Name of the core module to instantiate.
        top_module: Name of the top-level wrapper module.
        pinout: Optional custom pinout. If None, uses canonical pinout.

    Returns:
        Complete Verilog source for the wrapper module.
    """
    if pinout is None:
        pinout = get_canonical_pinout()

    lines = []
    lines.append("// TinyTapeout wrapper for ChipGate DTL safety gate")
    lines.append("// Generated by ChipGate TinyTapeoutPrep")
    lines.append("// This is a public demonstration design. It does not guarantee")
    lines.append("// silicon correctness, fabrication readiness, or physical safety.")
    lines.append("")
    lines.append(f"module {top_module} (")
    lines.append("    input  wire clk,")
    lines.append("    input  wire rst_n,")
    lines.append(f"    input  wire [{TT_INPUT_WIDTH - 1}:0] ui_in,")
    lines.append("    output wire [7:0] uo_out,")
    lines.append("    input  wire [7:0] uio_in,")
    lines.append("    output wire [7:0] uio_out,")
    lines.append("    output wire [7:0] uio_oe,")
    lines.append("    input  wire ena")
    lines.append(");")
    lines.append("")

    # Wire declarations for core signals
    lines.append("    // Core signal wires")
    for sig in INPUT_PINOUT:
        lines.append(f"    wire {sig};")
    for sig in OUTPUT_PINOUT:
        lines.append(f"    wire {sig};")
    lines.append("")

    # Input pin assignments
    lines.append("    // Input pin mapping")
    for sig, (_, pin) in INPUT_PINOUT.items():
        lines.append(f"    assign {sig} = {pin};")
    lines.append("")

    # Core instantiation
    lines.append("    // Core module instantiation")
    port_list = []
    for sig in INPUT_PINOUT:
        port_list.append(f"        .{sig}({sig})")
    for sig in OUTPUT_PINOUT:
        port_list.append(f"        .{sig}({sig})")

    lines.append(f"    {core_module} core (")
    lines.append(",\n".join(port_list))
    lines.append("    );")
    lines.append("")

    # Output pin assignments
    lines.append("    // Output pin mapping")
    for sig, (_, pin) in OUTPUT_PINOUT.items():
        lines.append(f"    assign {pin} = {sig};")

    # Assign reserved output pins to 0
    for idx in RESERVED_OUTPUTS:
        lines.append(f"    assign uo_out[{idx}] = 1'b0;")

    lines.append("")

    # Unused bidirectional pins driven low
    lines.append("    // Unused bidirectional pins")
    lines.append("    assign uio_out = 8'b0;")
    lines.append("    assign uio_oe  = 8'b0;")
    lines.append("")
    lines.append("endmodule")

    return "\n".join(lines)


def generate_core_verilog(
    module_name: str = "tiny_dtl_gate",
) -> str:
    """Generate the combinational DTL safety gate core module.

    Logic:
        actuator_enable = ai_output && verifier_ok && policy_ok
                          && sensor_ok && !timeout && !kill_switch && !reset
        blocked   = kill_switch || timeout || !verifier_ok || !policy_ok || !sensor_ok
        failsafe  = !actuator_enable
        approved  = actuator_enable
        evidence_pulse = actuator_enable
    """
    lines = []
    lines.append("// TinyTapeout DTL Safety Gate — Combinational Core")
    lines.append("// Generated by ChipGate TinyTapeoutPrep")
    lines.append("// Public demonstration design only.")
    lines.append("// Does not guarantee silicon correctness or physical safety.")
    lines.append("")
    lines.append(f"module {module_name} (")

    # Input ports
    input_sigs = list(INPUT_PINOUT.keys())
    output_sigs = list(OUTPUT_PINOUT.keys())

    port_decls = []
    for sig in input_sigs:
        port_decls.append(f"    input  wire {sig}")
    for sig in output_sigs:
        port_decls.append(f"    output wire {sig}")

    lines.append(",\n".join(port_decls))
    lines.append(");")
    lines.append("")

    # Core safety logic
    lines.append("    // Core DTL safety gate logic")
    lines.append(
        "    assign actuator_enable = ai_output && verifier_ok && policy_ok "
        "&& sensor_ok && !timeout && !kill_switch && !reset;"
    )
    lines.append("")

    # Status outputs
    lines.append("    // Status outputs")
    lines.append(
        "    assign blocked = kill_switch || timeout "
        "!verifier_ok || !policy_ok || !sensor_ok;"
    )
    # Fix: add && that was missing
    # Actually let me write it correctly:
    # Re-do this line properly
    lines[-1] = (
        "    assign blocked = kill_switch || timeout "
        "|| !verifier_ok || !policy_ok || !sensor_ok;"
    )
    lines.append(
        "    assign failsafe = !actuator_enable;"
    )
    lines.append(
        "    assign approved = actuator_enable;"
    )
    lines.append(
        "    assign evidence_pulse = actuator_enable;"
    )
    lines.append("")
    lines.append("endmodule")

    return "\n".join(lines)


def generate_fsm_verilog(
    module_name: str = "tiny_dtl_gate_fsm",
) -> str:
    """Generate an FSM variant of the DTL safety gate.

    States: IDLE -> PROPOSED -> VERIFYING -> APPROVED -> BLOCKED -> FAILSAFE

    This variant uses a clock and reset to implement state-machine-based
    gating with the same safety properties as the combinational version.
    """
    lines = []
    lines.append("// TinyTapeout DTL Safety Gate — FSM Variant")
    lines.append("// Generated by ChipGate TinyTapeoutPrep")
    lines.append("// Public demonstration design only.")
    lines.append("// Does not guarantee silicon correctness or physical safety.")
    lines.append("")
    lines.append(f"module {module_name} (")

    input_sigs = list(INPUT_PINOUT.keys())
    output_sigs = list(OUTPUT_PINOUT.keys())

    port_decls = []
    for sig in input_sigs:
        port_decls.append(f"    input  wire {sig}")
    for sig in output_sigs:
        port_decls.append(f"    output reg  {sig}")

    lines.append(",\n".join(port_decls))
    lines.append(");")
    lines.append("")

    # State encoding
    lines.append("    // FSM state encoding")
    lines.append("    localparam S_IDLE     = 3'd0;")
    lines.append("    localparam S_PROPOSED = 3'd1;")
    lines.append("    localparam S_VERIFYING = 3'd2;")
    lines.append("    localparam S_APPROVED = 3'd3;")
    lines.append("    localparam S_BLOCKED  = 3'd4;")
    lines.append("    localparam S_FAILSAFE = 3'd5;")
    lines.append("")
    lines.append("    reg [2:0] state;")
    lines.append("")

    # State transition logic
    lines.append("    // State transition")
    lines.append("    always @(*) begin")
    lines.append("        case (state)")
    lines.append("            S_IDLE: begin")
    lines.append("                if (reset)")
    lines.append("                    state = S_IDLE;")
    lines.append("                else if (kill_switch || timeout)")
    lines.append("                    state = S_FAILSAFE;")
    lines.append("                else if (ai_output)")
    lines.append("                    state = S_PROPOSED;")
    lines.append("                else")
    lines.append("                    state = S_IDLE;")
    lines.append("            end")
    lines.append("            S_PROPOSED: begin")
    lines.append("                if (reset)")
    lines.append("                    state = S_IDLE;")
    lines.append("                else if (kill_switch || timeout)")
    lines.append("                    state = S_FAILSAFE;")
    lines.append("                else if (verifier_ok && policy_ok && sensor_ok)")
    lines.append("                    state = S_VERIFYING;")
    lines.append("                else if (!verifier_ok || !policy_ok || !sensor_ok)")
    lines.append("                    state = S_BLOCKED;")
    lines.append("                else")
    lines.append("                    state = S_PROPOSED;")
    lines.append("            end")
    lines.append("            S_VERIFYING: begin")
    lines.append("                if (reset)")
    lines.append("                    state = S_IDLE;")
    lines.append("                else if (kill_switch || timeout)")
    lines.append("                    state = S_FAILSAFE;")
    lines.append("                else if (verifier_ok && policy_ok && sensor_ok)")
    lines.append("                    state = S_APPROVED;")
    lines.append("                else")
    lines.append("                    state = S_BLOCKED;")
    lines.append("            end")
    lines.append("            S_APPROVED: begin")
    lines.append("                if (reset || kill_switch || timeout")
    lines.append("                    || !verifier_ok || !policy_ok || !sensor_ok)")
    lines.append("                    state = S_FAILSAFE;")
    lines.append("                else")
    lines.append("                    state = S_APPROVED;")
    lines.append("            end")
    lines.append("            S_BLOCKED: begin")
    lines.append("                if (reset)")
    lines.append("                    state = S_IDLE;")
    lines.append("                else if (kill_switch || timeout)")
    lines.append("                    state = S_FAILSAFE;")
    lines.append("                else")
    lines.append("                    state = S_BLOCKED;")
    lines.append("            end")
    lines.append("            S_FAILSAFE: begin")
    lines.append("                if (reset)")
    lines.append("                    state = S_IDLE;")
    lines.append("                else")
    lines.append("                    state = S_FAILSAFE;")
    lines.append("            end")
    lines.append("            default: state = S_IDLE;")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("")

    # Output logic
    lines.append("    // Output logic")
    lines.append("    always @(*) begin")
    lines.append("        actuator_enable = 1'b0;")
    lines.append("        blocked = 1'b0;")
    lines.append("        failsafe = 1'b0;")
    lines.append("        approved = 1'b0;")
    lines.append("        evidence_pulse = 1'b0;")
    lines.append("        case (state)")
    lines.append("            S_IDLE: begin")
    lines.append("                failsafe = 1'b1;")
    lines.append("            end")
    lines.append("            S_PROPOSED: begin")
    lines.append("                blocked = 1'b1;")
    lines.append("            end")
    lines.append("            S_VERIFYING: begin")
    lines.append("                blocked = 1'b1;")
    lines.append("            end")
    lines.append("            S_APPROVED: begin")
    lines.append("                actuator_enable = 1'b1;")
    lines.append("                approved = 1'b1;")
    lines.append("                evidence_pulse = 1'b1;")
    lines.append("            end")
    lines.append("            S_BLOCKED: begin")
    lines.append("                blocked = 1'b1;")
    lines.append("            end")
    lines.append("            S_FAILSAFE: begin")
    lines.append("                failsafe = 1'b1;")
    lines.append("            end")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("")
    lines.append("endmodule")

    return "\n".join(lines)